### PR TITLE
Cyprian

### PR DESCRIPTION
**Pull request by cypriannde**
@ditahm6  please sir can you review my assignment and if is ok then you can commit it to the main branch

### CODE REVIEW

**Comment by ditahm6** [comment]
will docker ps -a | grep $container_name  give me both the name and status of a container?
update the script with the following is my suggestion
docker ps -a | grep "STATUS\|$container_name"

**Comment by clintoncf** [comment]
Yeah this command "docker ps -a | grep $container_name"
will display the container and status but
this command <docker ps -a | grep "STATUS|&container_name">
will display only the container name

**Comment by ditahm6** [comment]
@clintoncf && @cypriannde 
 Can you run this command <docker ps -a | grep "STATUS|&container_name">
will display only the container name

and show the screenshot of how it displays container name and status?

**Comment by clintoncf** [comment]
[image: container status check.png]

**Comment by cypriannde** [comment]
Sorry was taking Zack through GitHub

**Review by clintoncf — CHANGES_REQUESTED** [review]
I think it's great 
but I have done the complete version of the code

**Comment by clintoncf** [comment]
@ditahm6 
    The code you suggested works perfectly.  Thank you, Sir

**Review by clintoncf — COMMENTED** [review]
I think it's great.
but sir @ditahm6 has suggested a better code
and I have also written the complete version of the program

**Comment by cypriannde** [comment]
looks good with sir James code

**Pull request closed without merging**
